# -*- coding: utf-8 -*-
"""generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umbjnYhGKewPtHzzXXorYXSDHjrosAa5
"""

import os
import uuid
import random
from datetime import datetime, timezone

import numpy as np
import pandas as pd


# Helpers
def env_int(name: str, default: int) -> int:
    return int(os.getenv(name, default))


def env_float(name: str, default: float) -> float:
    return float(os.getenv(name, default))


def env_str(name: str, default: str) -> str:
    return os.getenv(name, default)


def parse_start_date(value: str) -> datetime:
    """Accepts 'YYYY-MM-DD' or full ISO8601."""
    return datetime.fromisoformat(value)


# Core generation
def generate_transactions(
    n: int,
    users: list[str],
    merchants: list[str],
    devices: list[str],
    start_date: datetime,
    window_days: int,
    rng: np.random.Generator,
) -> pd.DataFrame:
    seconds = 60 * 60 * 24 * window_days

    # Vectorized ID generation
    tx_ids = [str(uuid.uuid4()) for _ in range(n)]

    df = pd.DataFrame(
        {
            "transaction_id": tx_ids,
            "timestamp": pd.to_datetime(
                rng.integers(0, seconds, size=n),
                unit="s",
                origin=start_date,
            ),
            "user_id": rng.choice(users, size=n),
            "merchant_id": rng.choice(merchants, size=n),
            "device_id": rng.choice(devices, size=n),
            "amount": np.round(rng.exponential(50, size=n), 2),
            "country": rng.choice(["US", "CA", "UK"], size=n),
            "is_fraud": np.zeros(n, dtype=int),
        }
    )
    return df


def write_outputs(df: pd.DataFrame, output_dir: str, basename: str, fmt: str) -> str:
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f"{basename}.{fmt}")

    if fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif fmt == "csv":
        df.to_csv(out_path, index=False)
    else:
        raise ValueError("OUTPUT_FORMAT must be 'parquet' or 'csv'")

    # Marker file
    marker = os.path.join(output_dir, "_SUCCESS")
    with open(marker, "w", encoding="utf-8") as f:
        f.write(out_path)

    return out_path


def write_metadata(
    output_dir: str,
    out_path: str,
    seed: int,
    num_users: int,
    num_merchants: int,
    num_devices: int,
    num_transactions: int,
    fraud_rate: float,
    start_date: str,
    window_days: int,
    fmt: str,
    fraud_positive_rate_actual: float,
    extra: dict | None = None,
) -> None:
    metadata_path = os.path.join(output_dir, "metadata.json")
    payload = {
        "output_path": out_path,
        "output_format": fmt,
        "seed": seed,
        "num_users": num_users,
        "num_merchants": num_merchants,
        "num_devices": num_devices,
        "num_transactions": num_transactions,
        "fraud_rate_config": fraud_rate,
        "fraud_positive_rate_actual": fraud_positive_rate_actual,
        "start_date": start_date,
        "window_days": window_days,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    if extra:
        payload.update(extra)

    import json  # noqa: PLC0415

    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def main() -> None:
    # Config (env-driven)
    seed = env_int("SEED", 42)

    num_users = env_int("NUM_USERS", 100_000)
    num_merchants = env_int("NUM_MERCHANTS", 10_000)
    num_devices = env_int("NUM_DEVICES", 200_000)
    num_transactions = env_int("NUM_TRANSACTIONS", 1_000_000)

    # Target overall fraud rate (default 5%)
    fraud_rate = env_float("FRAUD_RATE", 0.05)
    TARGET_FRAUD_RATE = fraud_rate

    # Mechanism knobs
    RISKY_MERCHANT_PCT = env_float("RISKY_MERCHANT_PCT", 0.01)          # 1% merchants
    COMPROMISED_DEVICE_PCT = env_float("COMPROMISED_DEVICE_PCT", 0.005) # 0.5% devices
    HIGH_RISK_USER_PCT = env_float("HIGH_RISK_USER_PCT", 0.02)          # 2% users

    MERCHANT_RISK_MULT = env_float("MERCHANT_RISK_MULT", 6.0)
    DEVICE_RISK_MULT = env_float("DEVICE_RISK_MULT", 10.0)
    USER_RISK_MULT = env_float("USER_RISK_MULT", 3.0)

    AMOUNT_SPIKE_MULT = env_float("AMOUNT_SPIKE_MULT", 3.0)
    SPIKE_RATIO = env_float("SPIKE_RATIO", 5.0)
    CONTAGION_MULT = env_float("CONTAGION_MULT", 1.5)  # fraud yesterday boosts today
    BASE_FLOOR = env_float("BASE_FLOOR", 0.0005)  # 0.05% per txn floor

    start_date_str = env_str("START_DATE", "2025-01-01")
    window_days = env_int("WINDOW_DAYS", 30)

    output_dir = env_str("OUTPUT_DIR", "/data")
    output_format = env_str("OUTPUT_FORMAT", "parquet")  # parquet|csv
    output_basename = env_str("OUTPUT_BASENAME", "transactions")

    # Reproducibility
    np.random.seed(seed)
    random.seed(seed)
    rng = np.random.default_rng(seed)

    # Entities
    users = [f"u_{i}" for i in range(num_users)]
    merchants = [f"m_{i}" for i in range(num_merchants)]
    devices = [f"d_{i}" for i in range(num_devices)]

    # Generate base transactions
    start_date = parse_start_date(start_date_str)
    df = generate_transactions(
        n=num_transactions,
        users=users,
        merchants=merchants,
        devices=devices,
        start_date=start_date,
        window_days=window_days,
        rng=rng,
    )

    # Fraud pattern injection
    user_id_arr = df["user_id"].to_numpy()
    merchant_id_arr = df["merchant_id"].to_numpy()
    device_id_arr = df["device_id"].to_numpy()
    amount_arr = df["amount"].to_numpy()

    num_risky_merchants = max(1, int(num_merchants * RISKY_MERCHANT_PCT))
    num_compromised_devices = max(1, int(num_devices * COMPROMISED_DEVICE_PCT))
    num_high_risk_users = max(1, int(num_users * HIGH_RISK_USER_PCT))

    risky_merchants = set(rng.choice(merchants, size=num_risky_merchants, replace=False))
    compromised_devices = set(rng.choice(devices, size=num_compromised_devices, replace=False))
    high_risk_users = set(rng.choice(users, size=num_high_risk_users, replace=False))

    m_mult = np.where(np.isin(merchant_id_arr, list(risky_merchants)), MERCHANT_RISK_MULT, 1.0)
    d_mult = np.where(np.isin(device_id_arr, list(compromised_devices)), DEVICE_RISK_MULT, 1.0)
    u_mult = np.where(np.isin(user_id_arr, list(high_risk_users)), USER_RISK_MULT, 1.0)

    # Per-user baseline (median amount); spikes become more fraud-prone
    user_baseline = df.groupby("user_id")["amount"].median()
    baseline_arr = df["user_id"].map(user_baseline).to_numpy()
    spike = amount_arr > (SPIKE_RATIO * baseline_arr)
    a_mult = np.where(spike, AMOUNT_SPIKE_MULT, 1.0)

    # Combine propensities
    propensity = m_mult * d_mult * u_mult * a_mult

    # Convert propensity -> probability and calibrate to target fraud rate
    p = 0.01 * propensity
    mean_p = float(np.mean(p))
    scale = TARGET_FRAUD_RATE / mean_p if mean_p > 0 else 1.0
    p = np.clip(p * scale, 0.0, 0.99)

    # --- Pass 1: initial sample ---
    is_fraud_0 = (rng.random(size=len(p)) < p).astype(int)

    # Build per-user per-day fraud indicator from pass 1
    tmp = df[["user_id", "timestamp"]].copy()
    tmp["date"] = pd.to_datetime(tmp["timestamp"]).dt.date
    tmp["is_fraud_0"] = is_fraud_0

    user_day_fraud = tmp.groupby(["user_id", "date"])["is_fraud_0"].max().reset_index()

    # Create next-day contagion mapping: (user_id, date+1) -> 1
    user_day_fraud["date_next"] = (pd.to_datetime(user_day_fraud["date"]) + pd.Timedelta(days=1)).dt.date
    contagion_keys = set(
        zip(
            user_day_fraud.loc[user_day_fraud["is_fraud_0"] == 1, "user_id"],
            user_day_fraud.loc[user_day_fraud["is_fraud_0"] == 1, "date_next"],
        )
    )

    # Apply contagion multiplier to probabilities for affected (user, day)
    df_dates = pd.to_datetime(df["timestamp"]).dt.date.to_numpy()
    contagion_mask = np.array(
        [(u, d) in contagion_keys for u, d in zip(df["user_id"].to_numpy(), df_dates)],
        dtype=bool,
    )
    p2 = p * np.where(contagion_mask, CONTAGION_MULT, 1.0)
    p2 = np.clip(p2 + BASE_FLOOR, 0.0, 0.99)

    # Recalibrate to keep global fraud rate at TARGET_FRAUD_RATE
    mean_p2 = float(np.mean(p2))
    scale2 = TARGET_FRAUD_RATE / mean_p2 if mean_p2 > 0 else 1.0
    p2 = np.clip(p2 * scale2, 0.0, 0.99)

    # --- Pass 2: final sample ---
    df["is_fraud"] = (rng.random(size=len(p2)) < p2).astype(int)
    fraud_positive_rate_actual = float(df["is_fraud"].mean())

    # Persist outputs
    out_path = write_outputs(df, output_dir, output_basename, output_format)

    extra = {
        "fraud_mechanisms": {
            "target_fraud_rate": TARGET_FRAUD_RATE,
            "risky_merchant_pct": RISKY_MERCHANT_PCT,
            "compromised_device_pct": COMPROMISED_DEVICE_PCT,
            "high_risk_user_pct": HIGH_RISK_USER_PCT,
            "merchant_risk_mult": MERCHANT_RISK_MULT,
            "device_risk_mult": DEVICE_RISK_MULT,
            "user_risk_mult": USER_RISK_MULT,
            "amount_spike_mult": AMOUNT_SPIKE_MULT,
            "spike_ratio": SPIKE_RATIO,
            "contagion_mult": CONTAGION_MULT,
        }
    }

    write_metadata(
        output_dir=output_dir,
        out_path=out_path,
        seed=seed,
        num_users=num_users,
        num_merchants=num_merchants,
        num_devices=num_devices,
        num_transactions=num_transactions,
        fraud_rate=fraud_rate,
        start_date=start_date_str,
        window_days=window_days,
        fmt=output_format,
        fraud_positive_rate_actual=fraud_positive_rate_actual,
        extra=extra,
    )

    print(
        f"[event-generator] rows={len(df):,} fraud_positive_rate={fraud_positive_rate_actual:.4f} -> {out_path}"
    )


if __name__ == "__main__":
    main()