# -*- coding: utf-8 -*-
"""publish_latest_to_redis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyx6hOUe2zFRkdEodvYj1kDkk7bGlxXd
"""

import os
import json

import psycopg2
import redis


PGHOST = os.getenv("PGHOST", "postgres")
PGPORT = int(os.getenv("PGPORT", "5432"))
PGDATABASE = os.getenv("PGDATABASE", "fraud")
PGUSER = os.getenv("PGUSER", "fraud")
PGPASSWORD = os.getenv("PGPASSWORD", "fraud")

REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB = int(os.getenv("REDIS_DB", "0"))

KEY_PREFIX = os.getenv("KEY_PREFIX", "user")
BATCH_SIZE = max(1, int(os.getenv("BATCH_SIZE", "5000")))


def publish_row(
    pipe,
    user_id: str,
    txn_count: int,
    total_amount: float,
    avg_amount: float,
    distinct_merchants: int,
    distinct_devices: int,
    fraud_txn_count: int,
    fraud_rate: float,
    user_device_degree: int,
    user_merchant_degree: int,
    avg_device_user_degree: float,
    max_device_user_degree: int,
    avg_merchant_device_degree: float,
    max_merchant_device_degree: int,
):
    # Derived feature (keeps training/inference consistent)
    had_fraud_today = 1 if int(fraud_txn_count) > 0 else 0

    key = f"{KEY_PREFIX}:{user_id}:features"
    payload = {
        "user_id": user_id,
        "txn_count": int(txn_count),
        "total_amount": float(total_amount),
        "avg_amount": float(avg_amount),
        "distinct_merchants": int(distinct_merchants),
        "distinct_devices": int(distinct_devices),
        "fraud_txn_count": int(fraud_txn_count),
        "fraud_rate": float(fraud_rate),
        "had_fraud_today": int(had_fraud_today),

        # Graph features
        "user_device_degree": int(user_device_degree),
        "user_merchant_degree": int(user_merchant_degree),
        "avg_device_user_degree": float(avg_device_user_degree),
        "max_device_user_degree": int(max_device_user_degree),
        "avg_merchant_device_degree": float(avg_merchant_device_degree),
        "max_merchant_device_degree": int(max_merchant_device_degree),
    }
    pipe.set(key, json.dumps(payload))


def main():
    print(f"[publisher] BATCH_SIZE={BATCH_SIZE}")

    r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=REDIS_DB, decode_responses=True)

    conn = psycopg2.connect(
        host=PGHOST, port=PGPORT, dbname=PGDATABASE, user=PGUSER, password=PGPASSWORD
    )
    conn.autocommit = True

    published = 0
    try:
        with conn.cursor() as cur:
            print("[publisher] Publishing most recent feature row per user (DISTINCT ON).")

            cur.execute(
                """
                SELECT DISTINCT ON (user_id)
                  user_id,
                  txn_count,
                  total_amount,
                  avg_amount,
                  distinct_merchants,
                  distinct_devices,
                  fraud_txn_count,
                  fraud_rate,

                  user_device_degree,
                  user_merchant_degree,
                  avg_device_user_degree,
                  max_device_user_degree,
                  avg_merchant_device_degree,
                  max_merchant_device_degree
                FROM features_user_daily
                ORDER BY user_id, feature_date DESC
                """
            )
            print(f"[publisher] cursor.rowcount={cur.rowcount} (may be -1 for SELECT)")

            first = cur.fetchone()
            if first is None:
                raise RuntimeError("[publisher] Query returned 0 rows unexpectedly.")

            pipe = r.pipeline(transaction=False)

            publish_row(pipe, *first)
            published = 1

            for row in cur:
                publish_row(pipe, *row)
                published += 1

                if published % BATCH_SIZE == 0:
                    pipe.execute()
                    print(f"[publisher] Published {published:,} keys...")

            pipe.execute()

        dbsize = r.dbsize()
        print(f"[publisher] DONE. published={published:,} Redis DBSIZE={dbsize:,}")

        test_key = f"{KEY_PREFIX}:u_1:features"
        exists = r.exists(test_key)
        print(f"[publisher] EXISTS {test_key} = {exists}")
        if exists:
            print(f"[publisher] SAMPLE {test_key} = {r.get(test_key)}")

    finally:
        conn.close()


if __name__ == "__main__":
    main()