# -*- coding: utf-8 -*-
"""lgbm_nextday_trainer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5DqhkXIIK7qEWtBdF9UWYyEF2oh8uXf
"""

from __future__ import annotations

import os
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import psycopg2
import lightgbm as lgb
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    precision_recall_fscore_support,
    roc_auc_score,
    average_precision_score,
    precision_recall_curve,
)


DEFAULT_FEATURES = [
    "txn_count",
    "total_amount",
    "avg_amount",
    "distinct_merchants",
    "distinct_devices",
    "had_fraud_today",

    # Graph features
    "user_device_degree",
    "user_merchant_degree",
    "avg_device_user_degree",
    "max_device_user_degree",
    "avg_merchant_device_degree",
    "max_merchant_device_degree",
]

@dataclass(frozen=True)
class NextDayTrainConfig:
    # Postgres
    pghost: str = "postgres"
    pgport: int = 5432
    pgdatabase: str = "fraud"
    pguser: str = "fraud"
    pgpassword: str = "fraud"

    # Artifacts
    artifact_dir: str = "/artifacts"
    model_version: str = "lgbm_nextday_v2"

    # Optional time window filter over feature_date (inclusive)
    train_start_date: Optional[str] = None  # e.g. "2025-01-20"
    train_end_date: Optional[str] = None    # e.g. "2025-01-30"

    # Training behavior
    test_size: float = 0.2
    random_state: int = 42

    # Threshold selection policies
    recall_target: float = 0.95
    precision_target: float = 0.20

    # Drift baseline bins
    drift_bins: int = 10

    # Features
    features: Tuple[str, ...] = tuple(DEFAULT_FEATURES)


def choose_thresholds(
    y_true: np.ndarray,
    y_prob: np.ndarray,
    recall_target: float = 0.95,
    precision_target: float = 0.20,
) -> Tuple[dict, dict, dict]:
    """
    Returns:
      - best_f1: dict
      - by_recall: dict (max precision s.t. recall >= recall_target)
      - by_precision: dict (max recall s.t. precision >= precision_target)
    """
    prec, rec, thr = precision_recall_curve(y_true, y_prob)
    # precision_recall_curve returns thr of length (len(prec)-1)
    prec_t = prec[:-1]
    rec_t = rec[:-1]
    thr_t = thr

    # Best F1 across thresholds
    f1 = (2 * prec_t * rec_t) / np.clip((prec_t + rec_t), 1e-12, None)
    i_f1 = int(np.nanargmax(f1)) if len(f1) else 0
    best_f1 = {
        "thr": float(thr_t[i_f1]) if len(thr_t) else 0.5,
        "precision": float(prec_t[i_f1]) if len(prec_t) else 0.0,
        "recall": float(rec_t[i_f1]) if len(rec_t) else 0.0,
        "f1": float(f1[i_f1]) if len(f1) else 0.0,
    }

    # Recall policy: maximize precision subject to recall >= target
    mask_r = rec_t >= recall_target
    if np.any(mask_r):
        i_r = int(np.argmax(prec_t[mask_r]))
        idx_r = int(np.where(mask_r)[0][i_r])
        by_recall = {
            "recall_target": float(recall_target),
            "thr": float(thr_t[idx_r]),
            "precision": float(prec_t[idx_r]),
            "recall": float(rec_t[idx_r]),
            "f1": float(f1[idx_r]),
        }
    else:
        by_recall = {
            "recall_target": float(recall_target),
            "thr": None,
            "precision": None,
            "recall": None,
            "f1": None,
            "note": "No threshold achieves recall target on this eval set.",
        }

    # Precision policy: maximize recall subject to precision >= target
    mask_p = prec_t >= precision_target
    if np.any(mask_p):
        i_p = int(np.argmax(rec_t[mask_p]))
        idx_p = int(np.where(mask_p)[0][i_p])
        by_precision = {
            "precision_target": float(precision_target),
            "thr": float(thr_t[idx_p]),
            "precision": float(prec_t[idx_p]),
            "recall": float(rec_t[idx_p]),
            "f1": float(f1[idx_p]),
        }
    else:
        by_precision = {
            "precision_target": float(precision_target),
            "thr": None,
            "precision": None,
            "recall": None,
            "f1": None,
            "note": "No threshold achieves precision target on this eval set.",
        }

    return best_f1, by_recall, by_precision


def compute_baseline_histograms(X: pd.DataFrame, n_bins: int = 10) -> dict:
    """Compute per-feature histogram baselines for drift detection (quantile bins)."""
    q = np.linspace(0.0, 1.0, n_bins + 1)
    out: dict = {"version": 1, "n_bins": int(n_bins), "features": {}}

    for f in X.columns:
        arr = X[f].astype(float).to_numpy()
        edges = np.quantile(arr, q)
        edges = np.asarray(edges, dtype=float)

        # Enforce strictly increasing edges (handles constant/low-variance features)
        for i in range(1, len(edges)):
            if edges[i] <= edges[i - 1]:
                edges[i] = edges[i - 1] + 1e-9

        counts, _ = np.histogram(arr, bins=edges)
        total = float(np.sum(counts)) if np.sum(counts) else 1.0
        expected = (counts / total).astype(float).tolist()

        out["features"][f] = {
            "edges": edges.astype(float).tolist(),
            "expected": expected,
        }

    return out


def _connect(cfg: NextDayTrainConfig):
    return psycopg2.connect(
        host=cfg.pghost,
        port=cfg.pgport,
        dbname=cfg.pgdatabase,
        user=cfg.pguser,
        password=cfg.pgpassword,
    )


def load_training_data(cfg: NextDayTrainConfig) -> pd.DataFrame:
    query = """
    SELECT
      f.feature_date,
      f.user_id,
      f.txn_count,
      f.total_amount,
      f.avg_amount,
      f.distinct_merchants,
      f.distinct_devices,

      -- derived from today's feature row (keeps consistency with publisher/inference)
      CASE WHEN f.fraud_txn_count > 0 THEN 1 ELSE 0 END AS had_fraud_today,

      -- graph features (default to 0 if missing)
      COALESCE(f.user_device_degree, 0) AS user_device_degree,
      COALESCE(f.user_merchant_degree, 0) AS user_merchant_degree,
      COALESCE(f.avg_device_user_degree, 0) AS avg_device_user_degree,
      COALESCE(f.max_device_user_degree, 0) AS max_device_user_degree,
      COALESCE(f.avg_merchant_device_degree, 0) AS avg_merchant_device_degree,
      COALESCE(f.max_merchant_device_degree, 0) AS max_merchant_device_degree,

      COALESCE(l.fraud_label, 0) AS label
    FROM features_user_daily f
    LEFT JOIN (
      SELECT
        feature_date,
        user_id,
        CASE WHEN fraud_txn_count > 0 THEN 1 ELSE 0 END AS fraud_label
      FROM features_user_daily
    ) l
      ON l.user_id = f.user_id
    AND l.feature_date = f.feature_date + INTERVAL '1 day'
    """

    with _connect(cfg) as conn:
        print("[training] executing training query...", flush=True)
        df = pd.read_sql(query, conn)
        print(f"[training] loaded df rows={len(df)} cols={len(df.columns)}", flush=True)

    # Ensure feature_date is comparable
    df["feature_date"] = pd.to_datetime(df["feature_date"]).dt.date

    if cfg.train_start_date:
        start = pd.to_datetime(cfg.train_start_date).date()
        df = df[df["feature_date"] >= start]

    if cfg.train_end_date:
        end = pd.to_datetime(cfg.train_end_date).date()
        df = df[df["feature_date"] <= end]

    return df


def train_and_write_artifacts(cfg: NextDayTrainConfig) -> Dict[str, Any]:
    """
    Trains model + writes:
      - model.joblib
      - metrics.json
      - feature_list.json
      - baseline_hist.json
    Returns metrics dict.
    """
    os.makedirs(cfg.artifact_dir, exist_ok=True)

    df = load_training_data(cfg)
    features = list(cfg.features)

    df = df.dropna(subset=features + ["label"])
    X = df[features].astype(float)
    y = df["label"].astype(int)

    if len(df) == 0:
        raise RuntimeError("No training rows after filtering/dropping NaNs.")

    # Train/test split (stratified)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=cfg.test_size, random_state=cfg.random_state, stratify=y
    )

    # Handle imbalance with scale_pos_weight
    pos = max(1, int(y_train.sum()))
    neg = max(1, int((1 - y_train).sum()))
    scale_pos_weight = neg / pos

    model = lgb.LGBMClassifier(
        n_estimators=500,
        learning_rate=0.05,
        num_leaves=31,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=cfg.random_state,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight,
    )

    model.fit(X_train, y_train)
    proba = model.predict_proba(X_test)[:, 1]

    # Threshold policies from PR curve
    best_f1, thr_recall, thr_precision = choose_thresholds(
        y_true=y_test.to_numpy(),
        y_prob=proba,
        recall_target=float(cfg.recall_target),
        precision_target=float(cfg.precision_target),
    )

    # Default 0.5 threshold metrics
    preds_05 = (proba >= 0.5).astype(int)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_test, preds_05, average="binary", zero_division=0
    )

    metrics: Dict[str, Any] = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "train_start_date": cfg.train_start_date,
        "train_end_date": cfg.train_end_date,
        "model_type": "lightgbm_lgbmclassifier",
        "model_version": cfg.model_version,
        "rows_total": int(len(df)),
        "rows_train": int(len(X_train)),
        "rows_test": int(len(X_test)),
        "positive_rate": float(y.mean()),
        "scale_pos_weight": float(scale_pos_weight),
        "precision@0.5": float(prec),
        "recall@0.5": float(rec),
        "f1@0.5": float(f1),
        "roc_auc": float(roc_auc_score(y_test, proba)) if len(np.unique(y_test)) > 1 else None,
        "pr_auc": float(average_precision_score(y_test, proba)) if len(np.unique(y_test)) > 1 else None,
        "best_threshold_by_f1": best_f1,
        "threshold_by_recall_target": thr_recall,
        "threshold_by_precision_target": thr_precision,
        "features": features,
        "feature_importance_gain": {
            f: float(imp)
            for f, imp in zip(
                features,
                model.booster_.feature_importance(importance_type="gain"),
            )
        },
    }

    # Save artifacts
    model_path = os.path.join(cfg.artifact_dir, "model.joblib")
    joblib.dump(model, model_path)

    # Drift baselines (histograms)
    baselines = compute_baseline_histograms(
        X_train[features],
        n_bins=int(cfg.drift_bins),
    )
    baselines["generated_at_utc"] = datetime.now(timezone.utc).isoformat()
    baselines["model_version"] = cfg.model_version
    baselines["train_start_date"] = cfg.train_start_date
    baselines["train_end_date"] = cfg.train_end_date

    with open(os.path.join(cfg.artifact_dir, "baseline_hist.json"), "w", encoding="utf-8") as f:
        json.dump(baselines, f, indent=2)

    with open(os.path.join(cfg.artifact_dir, "metrics.json"), "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    with open(os.path.join(cfg.artifact_dir, "feature_list.json"), "w", encoding="utf-8") as f:
        json.dump(features, f, indent=2)

    print(f"[training] Saved model to {model_path}")
    print(f"[training] Metrics:\n{json.dumps(metrics, indent=2)}")

    return metrics

