# -*- coding: utf-8 -*-
"""load_to_postgres

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7XXQga2UTKGa485qrJR2mnsn168J1Nw
"""

import os
import sys
from datetime import datetime, timezone

import pandas as pd
import psycopg2
from psycopg2.extras import execute_values


DATA_PATH = os.getenv("DATA_PATH", "/data/transactions.parquet")
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "50000"))

PGHOST = os.getenv("PGHOST", "postgres")
PGPORT = int(os.getenv("PGPORT", "5432"))
PGDATABASE = os.getenv("PGDATABASE", "fraud")
PGUSER = os.getenv("PGUSER", "fraud")
PGPASSWORD = os.getenv("PGPASSWORD", "fraud")


COLUMNS = [
    "transaction_id",
    "timestamp",
    "user_id",
    "merchant_id",
    "device_id",
    "amount",
    "country",
    "is_fraud",
]


def connect():
    return psycopg2.connect(
        host=PGHOST,
        port=PGPORT,
        dbname=PGDATABASE,
        user=PGUSER,
        password=PGPASSWORD,
    )


def upsert_chunk(conn, df_chunk: pd.DataFrame) -> int:
    # Ensure column order & types
    df_chunk = df_chunk[COLUMNS].copy()
    # psycopg2 handles Python datetime; ensure timestamp is datetime
    if not pd.api.types.is_datetime64_any_dtype(df_chunk["timestamp"]):
        df_chunk["timestamp"] = pd.to_datetime(df_chunk["timestamp"])

    records = [tuple(x) for x in df_chunk.to_numpy()]

    sql = """
        INSERT INTO raw_transactions (
            transaction_id, timestamp, user_id, merchant_id, device_id, amount, country, is_fraud
        ) VALUES %s
        ON CONFLICT (transaction_id) DO NOTHING
    """

    with conn.cursor() as cur:
        execute_values(cur, sql, records, page_size=5000)
    conn.commit()
    return len(records)


def main():
    start = datetime.now(timezone.utc)
    if not os.path.exists(DATA_PATH):
        print(f"[ingestion] ERROR: DATA_PATH not found: {DATA_PATH}", file=sys.stderr)
        sys.exit(1)

    print(f"[ingestion] Reading parquet: {DATA_PATH}")
    df = pd.read_parquet(DATA_PATH)

    # Basic sanity
    missing = [c for c in COLUMNS if c not in df.columns]
    if missing:
        print(f"[ingestion] ERROR: Missing columns: {missing}", file=sys.stderr)
        sys.exit(1)

    total = len(df)
    print(f"[ingestion] Rows to load: {total:,} (chunk_size={CHUNK_SIZE:,})")

    conn = connect()
    loaded = 0
    try:
        for i in range(0, total, CHUNK_SIZE):
            chunk = df.iloc[i : i + CHUNK_SIZE]
            n = upsert_chunk(conn, chunk)
            loaded += n
            print(f"[ingestion] Loaded {loaded:,}/{total:,}")
    finally:
        conn.close()

    dur = (datetime.now(timezone.utc) - start).total_seconds()
    print(f"[ingestion] DONE. loaded={loaded:,} seconds={dur:.2f}")


if __name__ == "__main__":
    main()