# -*- coding: utf-8 -*-
"""__init__.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xbhSTv95GC37ZQlcMgm91GHm7D5vM1Ob
"""

# Shared package for the fraud detection system.