# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_tq3-9hiwnszZtjENCgiq8gEVxwrfGF
"""

import json
import logging
import os
import psycopg2
import signal
import sys
import time


from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any
from psycopg2.extras import execute_values
from kafka import KafkaConsumer, KafkaProducer
from kafka.errors import KafkaError


# Config helpers
def env_str(name: str, default: str) -> str:
    return os.getenv(name, default)


def env_int(name: str, default: int) -> int:
    return int(os.getenv(name, default))


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


# Logging
LOG_LEVEL = env_str("LOG_LEVEL", "INFO").upper()

logging.basicConfig(
    level=LOG_LEVEL,
    format="%(asctime)s %(levelname)s %(message)s",
)
logger = logging.getLogger("kafka-ingest-consumer")


# Runtime config
KAFKA_BOOTSTRAP_SERVERS = env_str("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
KAFKA_TOPIC = env_str("KAFKA_TOPIC", "transactions.raw")
KAFKA_GROUP_ID = env_str("KAFKA_GROUP_ID", "fraud-postgres-ingest")
AUTO_OFFSET_RESET = env_str("AUTO_OFFSET_RESET", "earliest")

KAFKA_ENABLE_AUTO_COMMIT = env_bool("KAFKA_ENABLE_AUTO_COMMIT", False)
KAFKA_POLL_TIMEOUT_MS = env_int("KAFKA_POLL_TIMEOUT_MS", 5000)
KAFKA_MAX_RECORDS_PER_POLL = env_int("KAFKA_MAX_RECORDS_PER_POLL", 1000)

PGHOST = env_str("PGHOST", "postgres")
PGPORT = env_int("PGPORT", 5432)
PGDATABASE = env_str("PGDATABASE", "fraud")
PGUSER = env_str("PGUSER", "fraud")
PGPASSWORD = env_str("PGPASSWORD", "fraud")

PG_CONNECT_RETRIES = env_int("PG_CONNECT_RETRIES", 30)
PG_CONNECT_RETRY_SLEEP_SEC = env_int("PG_CONNECT_RETRY_SLEEP_SEC", 2)

BATCH_SIZE = env_int("BATCH_SIZE", 1000)
CREATE_TABLE_IF_MISSING = env_bool("CREATE_TABLE_IF_MISSING", True)

DLQ_ENABLED = env_bool("DLQ_ENABLED", False)
DLQ_TOPIC = env_str("DLQ_TOPIC", "transactions.dlq")
DLQ_CLIENT_ID = env_str("DLQ_CLIENT_ID", "fraud-dlq-producer")

EXIT_ON_ERROR = env_bool("EXIT_ON_ERROR", False)


# Graceful shutdown
RUNNING = True


def _handle_shutdown(signum: int, frame: Any) -> None:
    global RUNNING
    logger.info("Received signal %s. Shutting down gracefully...", signum)
    RUNNING = False


signal.signal(signal.SIGINT, _handle_shutdown)
signal.signal(signal.SIGTERM, _handle_shutdown)


# Database helpers
def pg_dsn() -> str:
    return (
        f"host={PGHOST} "
        f"port={PGPORT} "
        f"dbname={PGDATABASE} "
        f"user={PGUSER} "
        f"password={PGPASSWORD}"
    )


def connect_postgres_with_retry():
    attempts = 0
    while True:
        try:
            conn = psycopg2.connect(pg_dsn())
            conn.autocommit = False
            logger.info(
                "Connected to Postgres at %s:%s db=%s user=%s",
                PGHOST,
                PGPORT,
                PGDATABASE,
                PGUSER,
            )
            return conn
        except Exception as exc:
            attempts += 1
            logger.warning(
                "Postgres connection failed (attempt %s/%s): %s",
                attempts,
                PG_CONNECT_RETRIES,
                exc,
            )
            if attempts >= PG_CONNECT_RETRIES:
                raise
            time.sleep(PG_CONNECT_RETRY_SLEEP_SEC)


@contextmanager
def get_cursor(conn):
    cur = conn.cursor()
    try:
        yield cur
    finally:
        cur.close()


def ensure_table_exists(conn) -> None:
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS raw_transactions (
        event_id TEXT PRIMARY KEY,
        event_time TIMESTAMP,
        timestamp TIMESTAMP,
        ingested_at TIMESTAMP NOT NULL DEFAULT NOW(),
        transaction_id TEXT NOT NULL UNIQUE,
        user_id TEXT NOT NULL,
        merchant_id TEXT NOT NULL,
        device_id TEXT NOT NULL,
        amount DOUBLE PRECISION NOT NULL,
        country TEXT NOT NULL,
        is_fraud INTEGER NOT NULL CHECK (is_fraud IN (0, 1))
    );
    """

    alter_statements = [
        "ALTER TABLE raw_transactions ADD COLUMN IF NOT EXISTS event_id TEXT;",
        "ALTER TABLE raw_transactions ADD COLUMN IF NOT EXISTS event_time TIMESTAMP;",
        "ALTER TABLE raw_transactions ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP;",
        "ALTER TABLE raw_transactions ADD COLUMN IF NOT EXISTS ingested_at TIMESTAMP NOT NULL DEFAULT NOW();",
    ]

    backfill_statements = [
        "UPDATE raw_transactions SET event_id = transaction_id WHERE event_id IS NULL;",
        "UPDATE raw_transactions SET event_time = timestamp WHERE event_time IS NULL AND timestamp IS NOT NULL;",
        "UPDATE raw_transactions SET timestamp = event_time WHERE timestamp IS NULL AND event_time IS NOT NULL;",
    ]

    index_statements = [
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_raw_transactions_event_id_unique ON raw_transactions(event_id);",
        "CREATE INDEX IF NOT EXISTS idx_raw_transactions_event_time ON raw_transactions(event_time);",
        "CREATE INDEX IF NOT EXISTS idx_raw_transactions_timestamp ON raw_transactions(timestamp);",
        "CREATE INDEX IF NOT EXISTS idx_raw_transactions_user_id ON raw_transactions(user_id);",
        "CREATE INDEX IF NOT EXISTS idx_raw_transactions_merchant_id ON raw_transactions(merchant_id);",
        "CREATE INDEX IF NOT EXISTS idx_raw_transactions_device_id ON raw_transactions(device_id);",
    ]

    with get_cursor(conn) as cur:
        cur.execute(create_table_sql)

        for stmt in alter_statements:
            cur.execute(stmt)

        for stmt in backfill_statements:
            cur.execute(stmt)

        for stmt in index_statements:
            cur.execute(stmt)

    conn.commit()
    logger.info("Ensured raw_transactions table, columns, backfills, and indexes exist.")


# Kafka helpers
def create_consumer() -> KafkaConsumer:
    consumer = KafkaConsumer(
        KAFKA_TOPIC,
        bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
        group_id=KAFKA_GROUP_ID,
        auto_offset_reset=AUTO_OFFSET_RESET,
        enable_auto_commit=KAFKA_ENABLE_AUTO_COMMIT,
        value_deserializer=lambda m: json.loads(m.decode("utf-8")),
        key_deserializer=lambda k: k.decode("utf-8") if k else None,
        consumer_timeout_ms=1000,  # allows loop to check RUNNING periodically
    )
    logger.info(
        "Connected to Kafka bootstrap=%s topic=%s group_id=%s",
        KAFKA_BOOTSTRAP_SERVERS,
        KAFKA_TOPIC,
        KAFKA_GROUP_ID,
    )
    return consumer


def create_dlq_producer() -> KafkaProducer | None:
    if not DLQ_ENABLED:
        return None

    producer = KafkaProducer(
        bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
        client_id=DLQ_CLIENT_ID,
        value_serializer=lambda v: json.dumps(v).encode("utf-8"),
        key_serializer=lambda v: v.encode("utf-8") if v is not None else None,
        acks="all",
        retries=5,
    )
    logger.info("DLQ producer enabled for topic=%s", DLQ_TOPIC)
    return producer


# Validation / normalization
REQUIRED_FIELDS = {
    "event_id",
    "event_time",
    "transaction_id",
    "user_id",
    "merchant_id",
    "device_id",
    "amount",
    "country",
    "is_fraud",
}


def parse_event_time(value: Any) -> datetime:
    if isinstance(value, datetime):
        dt = value
    elif isinstance(value, str):
        normalized = value.replace("Z", "+00:00")
        dt = datetime.fromisoformat(normalized)
    else:
        raise ValueError(f"Invalid event_time type: {type(value)}")

    # Normalize timezone-aware timestamps to naive UTC for Postgres TIMESTAMP.
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return dt


def normalize_event(event: dict[str, Any]) -> tuple:
    missing = REQUIRED_FIELDS - set(event.keys())
    if missing:
        raise ValueError(f"Missing required field(s): {sorted(missing)}")

    event_id = str(event["event_id"]).strip()
    transaction_id = str(event["transaction_id"]).strip()
    user_id = str(event["user_id"]).strip()
    merchant_id = str(event["merchant_id"]).strip()
    device_id = str(event["device_id"]).strip()
    country = str(event["country"]).strip()

    if not event_id:
        raise ValueError("event_id is empty")
    if not transaction_id:
        raise ValueError("transaction_id is empty")
    if not user_id:
        raise ValueError("user_id is empty")
    if not merchant_id:
        raise ValueError("merchant_id is empty")
    if not device_id:
        raise ValueError("device_id is empty")
    if not country:
        raise ValueError("country is empty")

    event_time = parse_event_time(event["event_time"])

    amount = float(event["amount"])
    if amount < 0:
        raise ValueError("amount must be >= 0")

    is_fraud = int(event["is_fraud"])
    if is_fraud not in (0, 1):
        raise ValueError("is_fraud must be 0 or 1")

    return (
        event_id,
        event_time,
        event_time,
        transaction_id,
        user_id,
        merchant_id,
        device_id,
        amount,
        country,
        is_fraud,
    )


# Insert logic
INSERT_SQL = """
INSERT INTO raw_transactions (
    event_id,
    event_time,
    timestamp,
    transaction_id,
    user_id,
    merchant_id,
    device_id,
    amount,
    country,
    is_fraud
)
VALUES %s
ON CONFLICT (event_id) DO NOTHING;
"""

def insert_batch(conn, records: list[tuple]) -> int:
    if not records:
        return 0

    with get_cursor(conn) as cur:
        execute_values(
            cur,
            INSERT_SQL,
            records,
            page_size=min(BATCH_SIZE, len(records)),
        )
    conn.commit()
    return len(records)


# Main loop
def main() -> None:
    logger.info("Starting kafka-ingest-consumer...")
    logger.info(
        "Config: topic=%s group_id=%s pg=%s:%s/%s batch_size=%s dlq=%s",
        KAFKA_TOPIC,
        KAFKA_GROUP_ID,
        PGHOST,
        PGPORT,
        PGDATABASE,
        BATCH_SIZE,
        DLQ_ENABLED,
    )

    conn = connect_postgres_with_retry()
    if CREATE_TABLE_IF_MISSING:
        ensure_table_exists(conn)

    consumer = create_consumer()
    dlq_producer = create_dlq_producer()

    total_seen = 0
    total_valid = 0
    total_inserted = 0
    total_invalid = 0

    try:
        while RUNNING:
            polled = consumer.poll(timeout_ms=KAFKA_POLL_TIMEOUT_MS, max_records=KAFKA_MAX_RECORDS_PER_POLL)

            if not polled:
                continue

            batch_records: list[tuple] = []
            invalid_in_poll = 0

            for topic_partition, messages in polled.items():
                for msg in messages:
                    total_seen += 1
                    raw_event = msg.value

                    try:
                        record = normalize_event(raw_event)
                        batch_records.append(record)
                        total_valid += 1
                    except Exception as exc:
                        invalid_in_poll += 1
                        total_invalid += 1
                        logger.warning(
                            "Invalid event skipped at partition=%s offset=%s: %s",
                            msg.partition,
                            msg.offset,
                            exc,
                        )
                        publish_to_dlq(
                            producer=dlq_producer,
                            raw_event=raw_event,
                            error_message=str(exc),
                            kafka_key=msg.key,
                        )

            if batch_records:
                try:
                    inserted_count = insert_batch(conn, batch_records)
                    total_inserted += inserted_count

                    if not KAFKA_ENABLE_AUTO_COMMIT:
                        consumer.commit()

                    logger.info(
                        "Committed batch: seen=%s valid=%s invalid=%s inserted=%s totals(seen=%s valid=%s invalid=%s inserted=%s)",
                        len(batch_records) + invalid_in_poll,
                        len(batch_records),
                        invalid_in_poll,
                        inserted_count,
                        total_seen,
                        total_valid,
                        total_invalid,
                        total_inserted,
                    )
                except Exception as exc:
                    conn.rollback()
                    logger.exception("Batch insert failed; offsets not committed: %s", exc)
                    if EXIT_ON_ERROR:
                        raise
                    time.sleep(2)

    except KeyboardInterrupt:
        logger.info("Interrupted by keyboard.")
    finally:
        logger.info(
            "Shutting down. Final totals: seen=%s valid=%s invalid=%s inserted=%s",
            total_seen,
            total_valid,
            total_invalid,
            total_inserted,
        )

        try:
            if dlq_producer is not None:
                dlq_producer.flush()
                dlq_producer.close()
        except Exception:
            logger.exception("Error while closing DLQ producer.")

        try:
            consumer.close()
        except Exception:
            logger.exception("Error while closing Kafka consumer.")

        try:
            conn.close()
        except Exception:
            logger.exception("Error while closing Postgres connection.")


if __name__ == "__main__":
    main()