# -*- coding: utf-8 -*-
"""retrain_controller

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xomxTcQreZiNOPcEPikDQkhhrXFRVD16
"""

import os
import time
import shutil
from datetime import datetime, timezone

import psycopg2

from common_fraud.training.lgbm_nextday_trainer import NextDayTrainConfig, train_and_write_artifacts


PGHOST = os.getenv("PGHOST", "postgres")
PGPORT = int(os.getenv("PGPORT", "5432"))
PGDATABASE = os.getenv("PGDATABASE", "fraud")
PGUSER = os.getenv("PGUSER", "fraud")
PGPASSWORD = os.getenv("PGPASSWORD", "fraud")

RETRAIN_INTERVAL_SEC = int(os.getenv("RETRAIN_INTERVAL_SEC", "86400"))  # daily
RUNS_DIR = os.getenv("RUNS_DIR", "/runs")
CHALLENGER_DIR = os.getenv("CHALLENGER_DIR", "/challenger")

# Optional training window
TRAIN_START_DATE = os.getenv("TRAIN_START_DATE")
TRAIN_END_DATE = os.getenv("TRAIN_END_DATE")

# Quality gates
MIN_TRAIN_ROWS = int(os.getenv("MIN_TRAIN_ROWS", "50000"))

# Training knobs
MODEL_VERSION_PREFIX = os.getenv("MODEL_VERSION_PREFIX", "lgbm_nextday")
RECALL_TARGET = float(os.getenv("RECALL_TARGET", "0.95"))
PRECISION_TARGET = float(os.getenv("PRECISION_TARGET", "0.20"))
DRIFT_BINS = int(os.getenv("DRIFT_BINS", "10"))

DDL = """
CREATE TABLE IF NOT EXISTS model_registry (
  model_version TEXT PRIMARY KEY,
  trained_at_utc TIMESTAMPTZ NOT NULL,
  train_start_date DATE,
  train_end_date DATE,
  train_rows BIGINT,
  roc_auc DOUBLE PRECISION,
  pr_auc DOUBLE PRECISION,
  f1_at_05 DOUBLE PRECISION,
  artifact_path TEXT NOT NULL,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS model_pointers (
  name TEXT PRIMARY KEY,            -- champion|challenger|last_good
  model_version TEXT NOT NULL,
  updated_at_utc TIMESTAMPTZ NOT NULL
);
"""


def _connect():
    return psycopg2.connect(
        host=PGHOST, port=PGPORT, dbname=PGDATABASE, user=PGUSER, password=PGPASSWORD
    )


def _ensure_tables(conn):
    with conn.cursor() as cur:
        cur.execute(DDL)
    conn.commit()


def _register_model(conn, metrics: dict, artifact_path: str):
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO model_registry(
              model_version, trained_at_utc, train_start_date, train_end_date,
              train_rows, roc_auc, pr_auc, f1_at_05, artifact_path, notes
            )
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (model_version) DO NOTHING
            """,
            (
                metrics.get("model_version"),
                metrics.get("generated_at_utc"),
                metrics.get("train_start_date"),
                metrics.get("train_end_date"),
                metrics.get("rows_train"),
                metrics.get("roc_auc"),
                metrics.get("pr_auc"),
                metrics.get("f1@0.5"),
                artifact_path,
                "auto_retrain",
            ),
        )
    conn.commit()


def _set_pointer(conn, name: str, model_version: str):
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO model_pointers(name, model_version, updated_at_utc)
            VALUES (%s, %s, NOW())
            ON CONFLICT (name) DO UPDATE
              SET model_version=EXCLUDED.model_version,
                  updated_at_utc=NOW()
            """,
            (name, model_version),
        )
    conn.commit()


def _publish_challenger(run_dir: str):
    os.makedirs(CHALLENGER_DIR, exist_ok=True)

    # Clean destination
    for fn in os.listdir(CHALLENGER_DIR):
        fp = os.path.join(CHALLENGER_DIR, fn)
        if os.path.isdir(fp):
            shutil.rmtree(fp)
        else:
            os.remove(fp)

    # Copy artifacts expected by inference-api
    for fn in ["model.joblib", "metrics.json", "feature_list.json", "baseline_hist.json"]:
        src = os.path.join(run_dir, fn)
        if not os.path.exists(src):
            raise RuntimeError(f"Missing artifact {src}")
        shutil.copy2(src, os.path.join(CHALLENGER_DIR, fn))


def run_once():
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    model_version = f"{MODEL_VERSION_PREFIX}_{ts}"
    run_dir = os.path.join(RUNS_DIR, model_version)
    os.makedirs(run_dir, exist_ok=True)

    cfg = NextDayTrainConfig(
        pghost=PGHOST,
        pgport=PGPORT,
        pgdatabase=PGDATABASE,
        pguser=PGUSER,
        pgpassword=PGPASSWORD,
        artifact_dir=run_dir,
        model_version=model_version,
        train_start_date=TRAIN_START_DATE,
        train_end_date=TRAIN_END_DATE,
        recall_target=RECALL_TARGET,
        precision_target=PRECISION_TARGET,
        drift_bins=DRIFT_BINS,
    )

    print(f"[retrain] training model_version={model_version} into {run_dir}", flush=True)
    metrics = train_and_write_artifacts(cfg)
    print(f"[retrain] training finished model_version={model_version}", flush=True)

    if int(metrics.get("rows_train", 0)) < MIN_TRAIN_ROWS:
        raise RuntimeError(
            f"Train rows {metrics.get('rows_train')} < MIN_TRAIN_ROWS={MIN_TRAIN_ROWS}; refusing to publish challenger"
        )

    print(f"[retrain] publishing challenger artifacts -> {CHALLENGER_DIR}")
    _publish_challenger(run_dir)

    with _connect() as conn:
        _ensure_tables(conn)
        _register_model(conn, metrics, artifact_path=run_dir)
        _set_pointer(conn, "challenger", model_version)

    print(f"[retrain] done. challenger={model_version}")


def main():
    os.makedirs(RUNS_DIR, exist_ok=True)
    os.makedirs(CHALLENGER_DIR, exist_ok=True)

    while True:
        try:
            run_once()
        except Exception as e:
            print(f"[retrain] ERROR: {e}")
        time.sleep(RETRAIN_INTERVAL_SEC)


if __name__ == "__main__":
    main()